#ifndef __PORT_H__
#define __PORT_H__

#include "main.h"

//LED PIN RB6

#define LED_HEATING_DR (GPIO_PORTB_DATA)
#define LED_HEATING_CR (GPIO_PORTB_CONTROL)
#define LED_HEATING_PIN (GPIO_PIN_6)

//SSD PINS
#define SSD_DATA_PORT_DR  (GPIO_PORTD_DATA)
#define SSD_DATA_PORT_CR  (GPIO_PORTD_CONTROL)

#define SSD_TENS_DR (GPIO_PORTA_DATA)
#define SSD_TENS_CR (GPIO_PORTA_CONTROL)
#define SSD_TENS_PIN (GPIO_PIN_3)

#define SSD_UNITS_DR  (GPIO_PORTA_DATA)
#define SSD_UNITS_CR  (GPIO_PORTA_CONTROL)
#define SSD_UNITS_PIN  (GPIO_PIN_4)

//PB PINS
#define PB_UP_PORT_DR (GPIO_PORTB_DATA)
#define PB_UP_PORT_CR (GPIO_PORTB_CONTROL)
#define PB_UP_PIN     (GPIO_PIN_4)

#define PB_DOWN_PORT_DR (GPIO_PORTB_DATA)
#define PB_DOWN_PORT_CR (GPIO_PORTB_CONTROL)
#define PB_DOWN_PIN     (GPIO_PIN_5)

#define PB_ON_OFF_PORT_DR (GPIO_PORTB_DATA)
#define PB_ON_OFF_PORT_CR (GPIO_PORTB_CONTROL)
#define PB_ON_OFF_PIN      (GPIO_PIN_3)

//HEATER PIN RC5
#define HEATER_PORT_DR (GPIO_PORTC_DATA)
#define HEATER_PORT_CR (GPIO_PORTC_CONTROL)
#define HEATER_PIN     (GPIO_PIN_5)

//COOLER/FAN PIN RC2
#define COOLER_PORT_DR (GPIO_PORTC_DATA)
#define COOLER_PORT_CR (GPIO_PORTC_CONTROL)
#define COOLER_PIN     (GPIO_PIN_2)

//I2C CONNECTION
#define ICLK RC3
#define IDAT RC4
#define TIDAT TRISC4



#endif // __PORT_H__
